services:
  postgres:
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=help_desk'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=pass'
    ports:
      - '5433:5432'

  sonarqube:
    image: sonarqube:10.3.0-community
    ports:
      - '9000:9000'