spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/help_desk?createDatabaseIfNotExist=true
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    username: username
    password: password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351